### ISSUE TITLE
Clean upstream project is unable to find pin declarations 

### ISSUE THREAD

**Issue by vepina** [WPIRoboticsEngineering/RBE3001_nucleo_firmware#11]
#defines in main.h (MISO, SERVO_X, etc.) cannot find the pin addresses (ex: PE_9) in the correct "PinNames.h" file for our board within directory:

"mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h" .

Our temporary solution is to explicitly include this header file in main.h as follows:

#include "../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h"

Peace, Love, and Robots,
Team 14

**Comment by madhephaestus** [comment]
Hey, can you review the Issue Reporting guidelines and make a PR (no need to demonstrate the error)

https://github.com/WPIRoboticsEngineering/RBE3001_nucleo_firmware#reporting-issues-with-the-template-code

**Comment by nag92** [comment]
I have figured out it is a switching branch problem. I was able to replicate the error my deploying mbed on one branch and switching to another. 
I have tried to remove all the files created by mbed deploy and rerunning it and cannot get it to work.
