### ISSUE TITLE
Upgrade to modern dependencies & tooling

### ISSUE THREAD

**Issue by WardBenjamin** [WPIRoboticsEngineering/RBE3001_nucleo_firmware#28]
Dependencies including [mbed-os](https://github.com/WPIRoboticsEngineering/mbed-os/issues/1) and arm-gcc are outdated and do not allow the use of modern language features, operating systems, etc.  Please see (https://github.com/WPIRoboticsEngineering/mbed-os/issues/1 for more mbed-os details.

Modern ARM GCC compilers can be easily installed to `/opt` from the [official ARM website](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain) using just `wget` and `tar`. The Launchpad PPA for gcc-arm-embedded is deprecated.

Eclipse 2017 can be replaced by a less-fragile installation of either VS Code (preferable) using either the current mbed-os toolchain or PlatformIO, or at the very minimum a more modern version of Eclipse (not preferable, but better).

**Comment by kid-a** [comment]
Thank you for opening this issue. The entire hardware infrastructure for RBE 3001 will be overhauled and modernized next year - we are working on this as we speak. The new hardware will likely come with a new development infrastructure and tooling. We will definitely take into consideration the upgrades suggested above. For now, I recommend closing this issue - we will not be able to take action on this before the summer break anyway.

**Comment by WardBenjamin** [comment]
Good to know, thank you! Can you share any details about the new hardware?

**Comment by alextac98** [comment]
> Good to know, thank you! Can you share any details about the new hardware?

We haven't really decided yet. We are looking into brushless motors and more specialized controllers, but no decision has been made yet.

**Comment by kid-a** [comment]
@WardBenjamin If you have any recommendations, of if you have worked with some components (e.g. motors) that you particularly liked, we would love to hear your inputs!

**Comment by madhephaestus** [comment]
We are looking at these motors:
https://odoo.cs.wpi.edu/shop/product/emax-gb2808-brushless-gimbal-motor-hollow-shaft-70kv-1194

these drivers:

https://odoo.cs.wpi.edu/shop/product/odrive-v3-6-24v-with-connectors-1120?search=odrive

and a Teensy 3.5 as the coordinator processor. From the teensy up will be exactly the same, except there will be torque limiting on each axis with torque sensing on each link based on the current draw by the motor.
